[package]
name = "perf_events"
version = "0.1.0"
authors = ["Adam Perry <adam.n.perry@gmail.com>"]
license = "MIT"

[dependencies]
errno = "0.2"
failure = "0.1"
failure_derive = "0.1"
libc = "0.2"
strum = "0.9"
strum_macros = "0.9"

[build-dependencies]
bindgen = "0.26"
